import { getPlaygroundHTML } from '../src/generators/playground';
import { RouteConfig, Schema } from '../src/types';

describe('Playground Generator', () => {
  const mockSchema: Schema = {
    type: 'object',
    properties: {
      id: { type: 'string' },
      name: { type: 'string' }
    }
  };

  const mockRoutes: Record<string, RouteConfig> = {
    'get:/api/users': {
      method: 'get',
      path: '/api/users',
      response: () => ({ success: true, data: [] }),
      schema: mockSchema
    },
    'post:/api/users': {
      method: 'post',
      path: '/api/users',
      response: () => ({ success: true, data: {} }),
      schema: mockSchema
    },
    'put:/api/users/:id': {
      method: 'put',
      path: '/api/users/:id',
      response: () => ({ success: true, data: {} }),
      schema: mockSchema
    },
    'delete:/api/users/:id': {
      method: 'delete',
      path: '/api/users/:id',
      response: () => ({ success: true, id: '123' }),
      schema: mockSchema
    },
    'patch:/api/users/:id': {
      method: 'patch',
      path: '/api/users/:id',
      response: () => ({ success: true, data: {} }),
      schema: mockSchema
    }
  };

  describe('getPlaygroundHTML', () => {
    it('should generate HTML with routes', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toBeDefined();
      expect(typeof html).toBe('string');
      expect(html.length).toBeGreaterThan(0);
    });

    it('should include basic HTML structure', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('<!DOCTYPE html>');
      expect(html).toContain('<html');
      expect(html).toContain('<head>');
      expect(html).toContain('<body>');
      expect(html).toContain('</html>');
    });

    it('should include title', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('Schemock Playground');
      expect(html).toContain('<title>Schemock Playground</title>');
    });

    it('should include routes section', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('<div class="routes">');
      expect(html).toContain('</div>');
    });

    it('should include footer', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('<div class="footer">');
      expect(html).toContain('Generated by');
      expect(html).toContain('Schemock');
    });

    it('should include health link', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('/health');
      expect(html).toContain('Health Status');
    });

    it('should include CSS styles', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('<style>');
      expect(html).toContain('</style>');
      expect(html).toContain('background-color:');
      expect(html).toContain('color:');
    });

    it('should include JavaScript', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('<script>');
      expect(html).toContain('</script>');
    });
  });

  describe('Route Cards', () => {
    it('should generate GET route card', () => {
      const routes: Record<string, RouteConfig> = {
        'get:/api/test': {
          method: 'get',
          path: '/api/test',
          response: () => ({ success: true }),
          schema: mockSchema
        }
      };

      const html = getPlaygroundHTML(routes);
      
      expect(html).toContain('GET');
      expect(html).toContain('/api/test');
      expect(html).toContain('method-get');
    });

    it('should generate POST route card', () => {
      const routes: Record<string, RouteConfig> = {
        'post:/api/test': {
          method: 'post',
          path: '/api/test',
          response: () => ({ success: true }),
          schema: mockSchema
        }
      };

      const html = getPlaygroundHTML(routes);
      
      expect(html).toContain('POST');
      expect(html).toContain('method-post');
    });

    it('should generate PUT route card', () => {
      const routes: Record<string, RouteConfig> = {
        'put:/api/test': {
          method: 'put',
          path: '/api/test',
          response: () => ({ success: true }),
          schema: mockSchema
        }
      };

      const html = getPlaygroundHTML(routes);
      
      expect(html).toContain('PUT');
      expect(html).toContain('method-put');
    });

    it('should generate DELETE route card', () => {
      const routes: Record<string, RouteConfig> = {
        'delete:/api/test': {
          method: 'delete',
          path: '/api/test',
          response: () => ({ success: true }),
          schema: mockSchema
        }
      };

      const html = getPlaygroundHTML(routes);
      
      expect(html).toContain('DELETE');
      expect(html).toContain('method-delete');
    });

    it('should generate PATCH route card', () => {
      const routes: Record<string, RouteConfig> = {
        'patch:/api/test': {
          method: 'patch',
          path: '/api/test',
          response: () => ({ success: true }),
          schema: mockSchema
        }
      };

      const html = getPlaygroundHTML(routes);
      
      expect(html).toContain('PATCH');
      expect(html).toContain('method-patch');
    });

    it('should include all HTTP method badges', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('method-get');
      expect(html).toContain('method-post');
      expect(html).toContain('method-put');
      expect(html).toContain('method-delete');
      expect(html).toContain('method-patch');
    });
  });

  describe('Route Details', () => {
    it('should include route card structure', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('class="route-card"');
      expect(html).toContain('class="route-header"');
      expect(html).toContain('class="route-details"');
    });

    it('should include tabs for each route', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('class="tabs"');
      expect(html).toContain('Try it out');
      expect(html).toContain('Schema');
      expect(html).toContain('Example Response');
    });

    it('should include expand icon', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('class="expand-icon"');
      expect(html).toContain('▼');
    });
  });

  describe('Request Body', () => {
    it('should include request body for POST', () => {
      const routes: Record<string, RouteConfig> = {
        'post:/api/test': {
          method: 'post',
          path: '/api/test',
          response: () => ({ success: true }),
          schema: mockSchema
        }
      };

      const html = getPlaygroundHTML(routes);
      
      expect(html).toContain('Request Body');
      expect(html).toContain('request-body-input');
    });

    it('should include request body for PUT', () => {
      const routes: Record<string, RouteConfig> = {
        'put:/api/test': {
          method: 'put',
          path: '/api/test',
          response: () => ({ success: true }),
          schema: mockSchema
        }
      };

      const html = getPlaygroundHTML(routes);
      
      expect(html).toContain('Request Body');
      expect(html).toContain('request-body-input');
    });

    it('should include request body for PATCH', () => {
      const routes: Record<string, RouteConfig> = {
        'patch:/api/test': {
          method: 'patch',
          path: '/api/test',
          response: () => ({ success: true }),
          schema: mockSchema
        }
      };

      const html = getPlaygroundHTML(routes);
      
      expect(html).toContain('Request Body');
      expect(html).toContain('request-body-input');
    });

    it('should not include request body for GET', () => {
      const routes: Record<string, RouteConfig> = {
        'get:/api/test': {
          method: 'get',
          path: '/api/test',
          response: () => ({ success: true }),
          schema: mockSchema
        }
      };

      const html = getPlaygroundHTML(routes);
      
      // GET should not have request body section
      expect(html).not.toContain('Request Body');
      expect(html).not.toContain('request-body-input');
    });

    it('should not include request body for DELETE', () => {
      const routes: Record<string, RouteConfig> = {
        'delete:/api/test': {
          method: 'delete',
          path: '/api/test',
          response: () => ({ success: true }),
          schema: mockSchema
        }
      };

      const html = getPlaygroundHTML(routes);
      
      // DELETE should not have request body section
      expect(html).not.toContain('Request Body');
      expect(html).not.toContain('request-body-input');
    });
  });

  describe('Schema Display', () => {
    it('should include schema section', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('Response Schema');
      expect(html).toContain('schema-body');
    });

    it('should include schema JSON', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('"type"');
      expect(html).toContain('"object"');
      expect(html).toContain('"properties"');
    });
  });

  describe('Example Response', () => {
    it('should include example response section', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('Example Response');
    });

    it('should include example JSON', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('"success"');
    });
  });

  describe('Actions', () => {
    it('should include send request button', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('Send Request');
      expect(html).toContain('btn-primary');
    });

    it('should include response section', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('Response');
      expect(html).toContain('response-section');
    });

    it('should include copy button', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('Copy');
      expect(html).toContain('btn-copy');
    });

    it('should include status code display', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('Status:');
      expect(html).toContain('status-code');
    });
  });

  describe('JavaScript Functions', () => {
    it('should include toggleRoute function', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('function toggleRoute');
      expect(html).toContain('classList.contains');
      expect(html).toContain('classList.add');
    });

    it('should include showTab function', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('function showTab');
      expect(html).toContain('tab-content');
    });

    it('should include tryItOut function', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('function tryItOut');
      expect(html).toContain('fetch(');
    });

    it('should include copyToClipboard function', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('function copyToClipboard');
      expect(html).toContain('navigator.clipboard.writeText');
    });
  });

  describe('Edge Cases', () => {
    it('should handle empty routes', () => {
      const html = getPlaygroundHTML({});
      
      expect(html).toBeDefined();
      expect(html).toContain('Schemock Playground');
    });

    it('should handle routes without schema', () => {
      const routes: Record<string, RouteConfig> = {
        'get:/api/test': {
          method: 'get',
          path: '/api/test',
          response: () => ({ success: true })
        }
      };

      const html = getPlaygroundHTML(routes);
      
      expect(html).toContain('No specific schema defined');
    });

    it('should handle complex paths with parameters', () => {
      const routes: Record<string, RouteConfig> = {
        'get:/api/users/:id/posts/:postId': {
          method: 'get',
          path: '/api/users/:id/posts/:postId',
          response: () => ({ success: true }),
          schema: mockSchema
        }
      };

      const html = getPlaygroundHTML(routes);
      
      expect(html).toContain('/api/users/:id/posts/:postId');
    });
  });

  describe('Responsive Design', () => {
    it('should include viewport meta tag', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('<meta name="viewport"');
      expect(html).toContain('width=device-width, initial-scale=1.0');
    });

    it('should use system fonts', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('-apple-system');
      expect(html).toContain('BlinkMacSystemFont');
    });
  });

  describe('Colors and Styling', () => {
    it('should define CSS variables', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain(':root');
      expect(html).toContain('--primary-color');
      expect(html).toContain('--success-color');
      expect(html).toContain('--get-color');
      expect(html).toContain('--post-color');
      expect(html).toContain('--put-color');
      expect(html).toContain('--delete-color');
    });

    it('should include method-specific colors', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('#61affe'); // GET color
      expect(html).toContain('#49cc90'); // POST color
      expect(html).toContain('#fca130'); // PUT color
      expect(html).toContain('#f93e3e'); // DELETE color
      expect(html).toContain('#50e3c2'); // PATCH color
    });
  });

  describe('Accessibility', () => {
    it('should include lang attribute on html', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('<html lang="en">');
    });

    it('should include charset meta tag', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('<meta charset="UTF-8">');
    });
  });

  describe('Multiple Routes', () => {
    it('should generate HTML for multiple routes', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      // Count route cards by looking for class="route-card"
      const routeCardMatches = html.match(/class="route-card"/g);
      expect(routeCardMatches).toBeDefined();
      expect(routeCardMatches!.length).toBe(5); // We have 5 routes in mockRoutes
    });

    it('should include all route paths', () => {
      const html = getPlaygroundHTML(mockRoutes);
      
      expect(html).toContain('/api/users');
      expect(html).toContain('/api/users/:id');
    });
  });
});
